-- =============================================================================
-- 0023_remove_avatars.sql
-- Originally removed the profile-photo feature's storage objects directly in
-- SQL. Supabase's storage.protect_delete() trigger now blocks
-- `delete from storage.objects` / `delete from storage.buckets` outright, so
-- that version can never run — and because it was DDL inside a transaction,
-- it took whatever else was batched in the same `supabase db push` down with
-- it. Found 2026-08-05, fixed 2026-08-06.
--
-- Decision (Rob, 2026-07-28): this product should not hold profile photographs
-- of law firm staff at all. Staff are enrolled by their employer rather than
-- signing up themselves, and the photo served no function in the certification
-- record. That reasoning is unchanged by any of the above — only the removal
-- MECHANISM was wrong.
--
-- The migration's own comment 3 (below, preserved) already argued that
-- touching auth.users.raw_user_meta_data from a migration is the wrong tool
-- and should be a one-off Admin API script instead. The same argument applies
-- to storage, once protect_delete() makes it non-optional: this migration is
-- now a no-op, and the actual deletion is
-- scripts/remove-avatars-bucket.ts, run once by hand per environment via the
-- Storage API (SUPABASE_SERVICE_ROLE_KEY), watched rather than automated,
-- because it is destructive and irreversible.
--
-- Numbering: written as 0014, renumbered to 0018, and renumbered again to 0023
-- on 2026-08-05 when this branch merged main. It collided with
-- 0018_provisioning_identity.sql. Nothing here touches
-- training_events_event_type_check, so the warning attached to 0017 does not
-- apply to this file.
--
-- Application code for the feature was removed in the same change that
-- originally added this migration:
--   - app/api/account/avatar/route.ts            (deleted)
--   - app/dashboard/settings/_components/avatar-upload.tsx (deleted)
--   - lib/avatars.ts                             (deleted — 0019's signed-URL
--     resolver, orphaned once the feature went away)
--   - avatar rendering in nav-pill.tsx, certification-forecast.tsx,
--     team-table.tsx, dashboard/page.tsx, dashboard/layout.tsx,
--     dashboard/settings/page.tsx
-- That part shipped and is not affected by this fix — only bucket removal was
-- blocked.
-- =============================================================================

-- Intentionally empty. See scripts/remove-avatars-bucket.ts for the actual
-- removal, run once per environment through the Storage API.
select 1;

-- ---------------------------------------------------------------------------
-- Preserved from the original migration — still true, still the right call,
-- just no longer actioned here.
--
-- NOTE — residual `avatar_url` / `avatar_path` keys in
-- auth.users.raw_user_meta_data.
--
-- Any user who uploaded a photo still carries an `avatar_url` value in their
-- user_metadata, and anyone who changed their photo after 0019 carries an
-- `avatar_path` instead (0019 introduced the second shape; lib/avatars.ts
-- resolved both). Those values are inert: no application code reads either
-- key, and once the script runs the object they point at no longer exists.
--
-- Deliberately not cleaned up here or in the script below. Writing to the
-- `auth` schema is discouraged outside the Auth service; if the keys should
-- be stripped, do it through `auth.admin.updateUserById` (spreading the
-- existing user_metadata minus `avatar_url`/`avatar_path`) as its own
-- one-off script.
-- ---------------------------------------------------------------------------
