-- =============================================================================
-- 0026_question_pool_v1.sql
-- ix-questionpool: replace the 8 placeholder questions with the reviewed
-- 50-question bank, 10 per lesson.
--
-- Why this matters: until now the pool (8) equalled courses.questions_per_attempt
-- (8), so every candidate saw an identical exam and an unlimited retake was a
-- second look at the same paper. At 50 the stratified selector in
-- lib/training/assessment.ts finally has something to choose from, and the
-- 1/2/2/1/2 lesson blueprint starts doing real work.
--
-- The old rows are DEACTIVATED, never deleted: quiz_sessions.question_ids and
-- quiz_attempts reference them, and a past attempt must keep pointing at the
-- exact text that was served at the time.
--
-- Source of truth for this content: .planning/question-bank.xlsx
-- Generated from that file; do not hand-edit the rows below. Regenerate instead.
--
-- STATUS: content is pending Katy's legal-accuracy review (ix-questionpool).
-- =============================================================================

do $$
declare
  v_course_id uuid;
  v_inserted  int;
  v_retired   int;
begin
  select id into v_course_id from public.courses order by created_at limit 1;

  if v_course_id is null then
    raise exception '0026: no course row found. The courses row is hand-created '
                    'in the Supabase dashboard and exists in no migration. '
                    'Create it before running this.';
  end if;

  -- Idempotence guard: the v1 bank uses durable L<n>:<topic> tags. The old seed
  -- used PLACEHOLDER:*. If the new tags are already present, this has run.
  if exists (
    select 1 from public.quiz_questions
    where course_id = v_course_id and section_tag like 'L_:%'
  ) then
    raise notice '0026: question bank v1 already present, skipping.';
    return;
  end if;

  -- 1. Retire the placeholder pool.
  update public.quiz_questions
     set is_active = false
   where course_id = v_course_id
     and is_active = true;
  get diagnostics v_retired = row_count;

  -- 2. Insert the reviewed bank.
  insert into public.quiz_questions
    (course_id, question_text, answers, correct_index, explanation, section_tag, lesson)
  values
    (v_course_id,
     'Which statement best describes an attorney''s duty regarding AI tools used by their staff?',
     '["Attorneys have partial duty to supervise AI tools because they are not people. Only the software company is responsible", "Attorneys must make reasonable efforts to ensure staff AI use is compatible with professional obligations", "Supervision duties apply only to licensed paralegals, not other staff", "AI tools are exempt from supervision requirements under all state bar rules"]'::jsonb,
     1,
     'Attorneys should make reasonable efforts to ensure the conduct of non-lawyer assistants, including their use of AI tools, is compatible with the lawyer''s professional obligations.',
     'L1:rule-53-duty',
     1),
    (v_course_id,
     'A staff member uploads a confidential client file to a public AI tool, and the summary it returns contains a case citation that does not exist. Which of the firm''s two core compliance concerns does this single incident raise?',
     '["Confidentiality only, because the upload is what exposed client data, and a citation nobody relied on causes no harm", "Accuracy only, because nobody outside the firm has read the file and the vendor''s terms forbid disclosure", "Both confidentiality and accuracy, because the upload and the fabricated citation are separate failures", "Neither yet, because the summary has not been used in client work and can still be discarded before anyone relies on it"]'::jsonb,
     2,
     'Lesson 1 treats confidentiality and accuracy as two distinct concerns needing separate attention. Uploading the file is a confidentiality breach on its own, and the fabricated citation is an accuracy failure on its own. Each of the other options is true as far as it goes but stops a step short: the upload really is the exposure, nobody may have read it yet, and the summary has not yet been used. None of that changes the fact that two separate failures have already happened.',
     'L1:two-pillars',
     1),
    (v_course_id,
     'A firm''s intake automation moves client data between systems without anyone pasting anything into a chat window. What determines whether it actually protects confidentiality?',
     '["Whether it was configured to use secure channels and approved by the firm", "That it is an automation rather than a chatbox, since automations are built for secure processing", "Whether the data stays within the United States", "Whether staff have been trained on how to run it"]'::jsonb,
     0,
     'Lesson 1 warns that automations can pose the same confidentiality risks as chatboxes when they are not set up correctly. Automations genuinely are built for secure, repeatable processes, data location is one of Lesson 5''s four vendor criteria, and training is one of Lesson 4''s three approval requirements. Each is a real factor. But the protection comes from the configuration and the firm''s approval, not from the category the tool falls into.',
     'L1:automation-config',
     1),
    (v_course_id,
     'A legal assistant asks an AI tool how a particular judge is likely to rule and repeats the answer to the client. Under the three compliance risks the course names, this is most directly an example of:',
     '["Unintentional disclosure of confidential information", "Reliance on inaccurate or hallucinated output", "A firm policy matter rather than an ethics matter", "Improper or unsupervised use of an AI tool"]'::jsonb,
     3,
     'Lesson 1''s third risk category is improper or unsupervised use, and its two named examples are relying on AI for legal advice without oversight and using AI for case predictions, which is exactly this. The other risks are genuinely present too: describing the matter may disclose client facts, and the prediction itself may be invented. Firm policy does also cover it. The question asks which fits most directly, and the course names this scenario by name.',
     'L1:risk-categories',
     1),
    (v_course_id,
     'The course traces how compliance risk develops: a tool is chosen, sensitive information is entered, output is generated, then the output is used in client work without review. Once information has already been entered into an unapproved tool, what can still be prevented?',
     '["The inaccurate output reaching the client, if the draft is verified before use", "Nothing, the breach is complete and the remaining steps no longer matter", "The confidentiality exposure, if the conversation is deleted promptly", "Both the exposure and the inaccuracy, if a supervising attorney is notified"]'::jsonb,
     0,
     'Lesson 2 explains that prompts may be retained, reviewed, or used to train future models, so the confidentiality exposure happens at the moment of entry and deleting the conversation afterward does not reach copies already held. What is still preventable is the second, separate failure: verification before the output reaches client work. Notifying the supervising attorney is genuinely required under Lesson 3, and it is the right next step, but it governs the response to the breach rather than reversing it.',
     'L1:risk-chain',
     1),
    (v_course_id,
     'Which best describes a non-attorney staff member''s own obligation?',
     '["None directly, since Rule 5.3 places the supervisory duty on the attorney", "To independently assess whether each AI tool meets the firm''s security standards", "To review all AI output for legal accuracy before it reaches the attorney", "To follow firm AI policy, avoid unauthorized legal advice, and flag compliance risks"]'::jsonb,
     3,
     'Rule 5.3 does place the supervisory duty on the attorney, which is what makes the answer denying any direct obligation half right. But Lesson 1 states the rule means support staff, not only lawyers, carry a direct responsibility to understand and uphold compliance. Lesson 4 draws the boundary on the other side: staff are explicitly not expected to determine the technical details of compliance. Lesson 3 gives attorneys, not staff, final responsibility for legal accuracy, though staff do review drafts for obvious errors.',
     'L1:staff-scope',
     1),
    (v_course_id,
     'A firm wants to summarize attorney notes into client-file records, the same way every time. Based on the two tool categories the course describes, which is appropriate and why?',
     '["A chatbox, because summarizing is a drafting task and chatboxes are built for drafting", "Either one, provided client names are removed first", "An automation, because the task is repeatable and can be routed through approved systems", "Either one, provided an attorney reviews the output before it is filed"]'::jsonb,
     2,
     'Lesson 1 describes automations as suited to repetitive or complex workflows, and Lesson 4 names summarizing attorney notes as something a vetted automation can safely handle. Summarizing genuinely is a drafting-style task and chatboxes genuinely are built for drafting, which is what makes the chatbox answer tempting, but the deciding factor is the route the data takes rather than the shape of the task. Removing names is not sufficient under Lesson 2, and attorney review is required either way without making an unapproved route acceptable.',
     'L1:tool-selection',
     1),
    (v_course_id,
     'A staff member notices a colleague using an AI tool in a way that may be inconsistent with firm policy, but is not certain the policy applies. Under the course''s treatment of shared responsibility, the appropriate response is to:',
     '["Say nothing, since raising an uncertain concern could unfairly implicate a colleague", "Raise the question, because flagging a possible risk does not require being certain it is one", "Wait to see whether it happens again, so the concern is better supported before raising it", "Handle it privately with the colleague and avoid involving a supervisor"]'::jsonb,
     1,
     'Lesson 1 states that every member of the firm shares responsibility, that anyone unsure about a process should speak up, and that open communication prevents mistakes before they happen. Fairness to a colleague is a real consideration and a repeated pattern really is more persuasive evidence. Speaking to the colleague directly is in fact what Lesson 4 recommends for an unapproved workflow, but the course pairs that with checking policy or the supervising attorney rather than keeping it private, and waiting for a second occurrence leaves the first uncorrected.',
     'L1:speaking-up',
     1),
    (v_course_id,
     'The course notes that AI compliance failures can harm clients, damage the firm''s reputation, and lead to ethical violations. Which statement about those consequences is accurate?',
     '["They arise only once the AI output is filed with a court", "They attach to the supervising attorney but not to non-attorney staff", "They are substantially mitigated when the staff member acted in good faith", "They can arise from a single unreviewed output, whether or not it is ever filed"]'::jsonb,
     3,
     'Lesson 1''s own example is a client harmed after AI-generated content went out with bogus citations and incoherent content, which does not require a filing. Filings are indeed where sanctions are most visible, formal bar discipline does run to licensed attorneys, and good faith does bear on how a matter is ultimately treated. But the course locates the harm at the point the work reaches the client, makes compliance a shared responsibility, and states in Lesson 3 that unintentional mistakes do not absolve anyone of responsibility.',
     'L1:consequences',
     1),
    (v_course_id,
     'The course insists confidentiality and accuracy are very different concerns requiring separate attention. What follows from treating them separately?',
     '["A workflow that fully protects confidentiality still needs its own verification step", "A verified output can be shared through any tool, since accuracy was the risk being managed", "Confidentiality governs client data while accuracy governs court filings", "Addressing one generally addresses the other, since both stem from unsupervised use"]'::jsonb,
     0,
     'Lesson 1 separates the two pillars precisely because a fix for one is not a fix for the other. A firm-approved automation protects the data route but says nothing about whether the output is factually right, which is why Lesson 3 treats verification as non-negotiable even inside approved workflows. Unsupervised use genuinely does feed both, and filings genuinely are where accuracy failures cost the most, but neither observation collapses the two concerns into one.',
     'L1:pillars-independent',
     1),
    (v_course_id,
     'Before allowing staff to use an AI tool that processes client information, the supervising attorney should:',
     '["Review only the tool''s marketing page, since vendors are required to disclose material security limitations there", "Require staff to sign a personal liability waiver, so responsibility for any disclosure sits with the individual user", "Notify the state bar and await written guidance before any staff member uses the tool on client matters", "Evaluate the tool''s data retention practices, confidentiality protections, and terms of service"]'::jsonb,
     3,
     'Client data is subject to confidentiality obligations under Rule 1.6. An attorney must assess whether an AI vendor''s data handling practices are compatible with those obligations before allowing staff use.',
     'L2:vendor-assessment',
     2),
    (v_course_id,
     'A staff member removes the client''s name, then enters these facts into a consumer chatbot: entered the country in 1998, six U.S. citizen children, a child with a rare genetic disorder treated at a named hospital, a prior removal order, and a recent workplace-raid arrest. Has confidentiality been protected?',
     '["No, because the combination of details can reasonably identify the client", "No, but only because the hospital was named", "Yes, because no name, address, or file number was entered", "Yes, because each fact on its own is too general to identify anyone"]'::jsonb,
     0,
     'This is Lesson 2''s central scenario. Confidentiality extends to any information that could reasonably identify a client even when the name is never mentioned, and the lesson''s point is that several unique details together are enough for someone to recognize the client, especially in a smaller community or an unusual case. Removing direct identifiers is a real step, any single fact here really is fairly general, and the named hospital really is especially identifying. None of those is the reason. The accumulation is.',
     'L2:identifiability',
     2),
    (v_course_id,
     'A staff member enters no client facts at all, and asks a public chatbot to critique the firm''s planned argument for challenging a prior removal order. Under the course''s confidentiality rules this is:',
     '["A breach only if the chatbot retains the prompt for training, since exposure requires the data to persist somewhere", "A breach, because attorney strategy and work product must stay inside approved systems", "Acceptable, because no client information was entered and the question describes only a legal theory", "Acceptable, because legal arguments become public once they are filed"]'::jsonb,
     1,
     'Lesson 2 lists attorney strategy disclosure as a distinct breach alongside direct entry of client data and unique fact patterns, and its sorting exercise places the plan to challenge a prior removal order in the identifying column. It is literally true that no client data was entered, filed arguments really do enter the public record, and retention really is the mechanism of exposure. But mental impressions and planned arguments are privileged before filing, and the breach occurs on entry rather than waiting on proof of what the vendor did with the prompt.',
     'L2:strategy-disclosure',
     2),
    (v_course_id,
     'A staff member pastes a client summary into a consumer chatbot, immediately realizes the mistake, and deletes the conversation. The accurate assessment is:',
     '["The risk is resolved, since the conversation no longer exists in the account and the vendor honors deletion requests", "The risk is unchanged, since deletion only hides the conversation and never reaches the vendor''s own storage", "The risk is reduced, but the disclosure already occurred, because prompts may be retained or used for training", "The risk depends on whether the account was a paid business tier, since paid plans commonly exclude prompts from training"]'::jsonb,
     2,
     'Lesson 2 explains that many platforms retain, review, or use prompts to train future models, so the exposure happens when the information is entered. Deleting really does remove it from the visible account and is worth doing, deletion really does have limited practical reach, and account tier really does affect vendor terms. Lesson 4 addresses that last point directly: a business label still requires specific firm approval rather than settling the question on its own.',
     'L2:retention',
     2),
    (v_course_id,
     'Which of these could a staff member enter into a non-approved AI tool without breaching client confidentiality?',
     '["A client''s medical condition with the name and date removed", "The firm''s planned argument in a pending matter, which will become public when it is filed anyway", "A general procedural question, such as how a change of address is filed", "A case''s fact pattern with the dates and locations altered"]'::jsonb,
     2,
     'Lesson 2''s sorting exercise places a generic procedural question in the not-identifying column, because it carries no client data and no attorney strategy. De-identification and altering details are both real techniques that genuinely reduce risk, and eventual public filing is real too. But the lesson''s whole point is that a distinctive fact pattern survives de-identification, and strategy is privileged regardless of what is stripped out of it.',
     'L2:non-identifying',
     2),
    (v_course_id,
     'A staff member is unsure whether a workflow involving client data is approved, has checked firm policy without finding an answer, and has asked a colleague who was also unsure. The course''s next step is to:',
     '["Proceed, since a documented good-faith effort to check was made", "Proceed with client identifiers removed, as a reasonable middle course", "Defer the task until the firm publishes updated policy", "Escalate to a supervising attorney"]'::jsonb,
     3,
     'Lesson 2 gives a three-step path: stop and ask, check firm policy, then escalate to a supervising attorney if doubt remains, describing escalation as expected rather than merely permitted. Documenting the effort is good practice, removing identifiers is a genuine risk reduction, and waiting is certainly safer than proceeding. Each of those leaves the question unresolved, though, when the course supplies a way to resolve it.',
     'L2:escalation-path',
     2),
    (v_course_id,
     'What makes a consumer AI chatbox riskier for client information than an approved firm automation?',
     '["Chatboxes produce lower-quality output than automations do, and unreviewed drafts are how errors reach clients", "Chatboxes send data to a system that may retain or train on it, outside firm-controlled systems", "Chatboxes are free, and free tools have weaker security by definition", "Chatboxes cannot be audited after the fact, so a firm cannot show a regulator what was disclosed"]'::jsonb,
     1,
     'Lesson 2 identifies retention, review, and model training as the mechanism, and Lesson 4 contrasts that with automations keeping data inside firm-controlled systems. Output quality is a real chatbox weakness, though it belongs to the accuracy pillar rather than confidentiality. Free tiers really do tend to carry weaker terms, and auditability really is a gap. None of those is the route the data takes, which is what the course treats as decisive.',
     'L2:chatbox-mechanism',
     2),
    (v_course_id,
     'The course notes that combined details are especially likely to identify a client in smaller communities or unusual cases. What does that imply for a staff member deciding what is safe to enter?',
     '["Facts are safe to enter as long as the firm practices in a large metropolitan area", "Only immigration and family matters call for this level of caution", "The same set of facts can be identifying in one matter and not in another", "The test is whether the staff member personally recognizes the client from the facts"]'::jsonb,
     2,
     'Lesson 2 makes identifiability depend on context, which is exactly why the same facts can be safe in one matter and identifying in another. Population size genuinely does dilute identifiability, the lesson''s own worked example is an immigration matter with unusually distinctive facts, and recognizability really is the underlying idea. But none of those yields a category of facts that is always safe, and the standard is whether someone could reasonably identify the client rather than whether this particular reader happens to.',
     'L2:context-dependence',
     2),
    (v_course_id,
     'A staff member types no client details, but uploads a redacted PDF of a client file to a consumer AI tool for summarizing. Under the course''s rules this is:',
     '["A confidentiality risk, because the document reaches an external system regardless of redaction", "A confidentiality risk only if the redaction was performed improperly", "Acceptable, since redaction removes the confidential content", "Acceptable, since uploading a file is not the same as entering information into a prompt"]'::jsonb,
     0,
     'Lesson 1 names failing to review and uploading confidential documents to AI platforms as a form of unintentional disclosure, and Lesson 2''s concern is the external system rather than the method of input. Redaction is a real protective measure, improper redaction is a well-documented failure mode, and uploading does feel different from typing. But a redacted document still carries the fact pattern Lesson 2 warns about, and the upload itself puts it outside firm-controlled systems.',
     'L2:document-upload',
     2),
    (v_course_id,
     'A firm has a signed confidentiality agreement with an AI vendor. A staff member wants to use a different product from that same vendor. May they?',
     '["Not without confirming that the workflow itself is firm-approved", "Yes, the agreement covers the vendor and therefore covers its products", "Yes, provided the new product sits on the same account and billing relationship", "Not until the agreement is renewed to name the new product specifically"]'::jsonb,
     0,
     'Lesson 2 instructs staff to follow firm policy and vendor agreements, and Lesson 4 makes approval a property of the workflow, requiring design and security review, a vendor agreement, and policy and training together. Vendor-level agreements really are common and really do cover a lot, shared accounts often do share terms, and amending the agreement is a sensible step someone should take. But the staff member''s obligation is to confirm firm approval, not to reason about contract scope, which Lesson 4 places outside their role.',
     'L2:vendor-scope',
     2),
    (v_course_id,
     'A paralegal uses an AI tool to draft a client letter and sends it to the client without attorney review. This most likely creates:',
     '["No issue. The paralegal is responsible for their own work, and support staff routinely send routine correspondence", "No issue if the firm has previously approved the AI tool", "A potential ethics violation if the content is inaccurate or misleading", "An issue only if the client complains in writing, since ethics complaints require a client to raise them"]'::jsonb,
     2,
     'The attorney remains responsible for supervising non-lawyer work product, including AI-assisted drafts. Sending unreviewed AI output to a client can violate Rule 5.3 if the content causes harm.',
     'L3:unreviewed-output',
     3),
    (v_course_id,
     'Which is the most significant risk when staff use an AI tool to research case law?',
     '["AI research tools are slower than traditional legal databases", "AI tools always produce perfectly accurate citations and may replace attorneys if we are not careful", "AI-generated case citations may be fabricated: a phenomenon called hallucination", "Research tasks are not subject to attorney supervision requirements"]'::jsonb,
     2,
     'AI language models can generate plausible-looking but entirely fictitious case citations. This has led to real sanctions in documented cases (e.g., Mata v. Avianca). Every AI-generated citation must be verified.',
     'L3:fabricated-citations',
     3),
    (v_course_id,
     'If a staff member discovers that an AI tool has produced a significant error in a client document, the correct first step is:',
     '["Delete the document and start over with a different AI tool", "Correct the error themselves without escalating to the attorney", "Document the error internally and continue using the tool as normal", "Immediately notify the supervising attorney"]'::jsonb,
     3,
     'Errors in client documents must be escalated to the supervising attorney promptly. The attorney bears responsibility under Rule 5.3 and must decide how to proceed — including whether to notify the client.',
     'L3:error-escalation',
     3),
    (v_course_id,
     'Which of the following is the most accurate description of an AI "hallucination" in a legal context?',
     '["An AI tool that produces visual content without authorization", "Bias embedded in an AI model''s training data, which can distort how facts are characterized", "An AI tool misreading scanned or handwritten documents and carrying the error into a summary", "AI generating false or fabricated information presented confidently as fact"]'::jsonb,
     3,
     'Hallucination refers to AI systems generating information that sounds authoritative but is factually incorrect or entirely invented — such as case names, citations, statutes, or dates that do not exist.',
     'L3:hallucination-definition',
     3),
    (v_course_id,
     'A staff member verifies three of the five citations in an AI-generated brief and cannot locate the other two. Before passing the draft to the supervising attorney, they should:',
     '["Note clearly which citations could not be independently verified", "Remove the two unverified citations, so the draft contains only verified sources", "Mark the draft verified, since the missing two may simply sit in a database they lack access to", "Pass it along without comment, since the attorney verifies everything before filing"]'::jsonb,
     0,
     'Lesson 3''s verification workflow has a dedicated step for communicating unverified elements to the supervising attorney, and the lesson warns never to represent AI output as checked unless it was personally verified. Database coverage really does vary, the attorney really does hold ultimate responsibility, and pruning shaky citations is a defensible instinct. But Lesson 3 lists assuming the attorney will catch all errors as non-compliant, and quietly removing citations denies the attorney the information needed to decide.',
     'L3:communicating-unverified',
     3),
    (v_course_id,
     'An AI-generated filing cites only real, correctly stated authority, but omits the certificate of service and uses the wrong font size. This is:',
     '["Not an accuracy problem, since every citation checks out and the substance of the argument is unaffected", "An accuracy problem, because filing rule violations sit alongside fictitious citations and misstated holdings", "A formatting matter for administrative staff rather than a compliance concern, correctable on refiling", "A concern only if the court actually rejects the filing, since many clerks accept minor deviations"]'::jsonb,
     1,
     'Lesson 3 lists filing rule violations as one of three things that go wrong when verification is skipped, next to fictitious citations and misstated holdings, noting such errors can get filings rejected, delayed, or dismissed. The citations here really are fine, formatting really is normally administrative work, and the consequence really does materialize on rejection. The lesson still treats compliance with court rules as part of the verification obligation rather than a separate clerical task.',
     'L3:filing-rules',
     3),
    (v_course_id,
     'An AI summary cites a real, correctly named case, but describes its holding as the opposite of what the court decided. Compared with a fabricated citation, this error is:',
     '["Less serious, because the case exists and can be located", "More serious, because it cannot be caught by checking whether the case exists", "Not a hallucination at all, since nothing was invented", "Equally serious, because misrepresenting the law is its own form of hallucination"]'::jsonb,
     3,
     'Lesson 3''s Spot the Hallucination exercise treats an AI that summarizes a real case but misstates the holding as another form of hallucination, and says misrepresenting the law is just as risky. It is genuinely true that this error survives an existence check, which is what makes it dangerous in day-to-day practice, and genuinely true that the citation itself is real. But the course frames the two as equally serious rather than ranking them, and both are hallucinations, because the assertion about the law was invented even though the case name was not.',
     'L3:misstated-holding',
     3),
    (v_course_id,
     'A brief is filed containing a fictitious citation. A staff member did the research, the attorney signed it, and the AI vendor''s terms disclaim accuracy. Who bears responsibility for the filing?',
     '["The staff member, who performed the research and passed it along without flagging it", "The AI vendor, whose tool generated the citation and whose terms disclaim accuracy", "The supervising attorney, who is responsible for verifying authority before filing", "Nobody, provided none of them knew the citation was fictitious and the error was corrected promptly"]'::jsonb,
     2,
     'Lesson 3''s knowledge check puts this squarely: attorneys are ultimately responsible for verifying the accuracy of legal authorities before filing, as part of their professional and ethical obligations. Staff really do carry duties to research carefully and flag what they could not verify, the vendor really did generate the text, and disclaimers really do exist. But the lesson states vendors are not responsible for the legal accuracy of filings, and that unintentional mistakes do not absolve anyone of responsibility.',
     'L3:ultimate-responsibility',
     3),
    (v_course_id,
     'A staff member checks an AI-generated citation by asking the same AI tool whether the case is real. It confirms that the case exists. Under Lesson 3, the citation is:',
     '["Not verified, but acceptable if the attorney is told the check was informal and can repeat it before filing", "Not verified, because verification requires a trusted, authoritative source outside the tool", "Verified, since the tool confirmed it on a separate query made independently of the first", "Verified, provided the second answer matched the first"]'::jsonb,
     1,
     'Lesson 3 requires every citation and legal authority to be checked against a trusted, authoritative source, naming Westlaw and Lexis, and describes the step as independent verification. A second query really is an attempt at cross-checking and consistency really is mildly reassuring, but neither is independent of the system that produced the error. Disclosing that a check was informal is genuinely required if the draft moves forward, though it does not turn an unverified citation into a verified one.',
     'L3:independent-source',
     3),
    (v_course_id,
     'Lesson 3 divides verification work between staff and the supervising attorney. Which task belongs to staff?',
     '["Deciding whether the draft complies with court rules and may be filed", "Reviewing the draft for obvious errors and flagging unverified content", "Confirming that each legal argument is genuinely supported by the authority cited", "Determining which authorities are binding in the relevant jurisdiction"]'::jsonb,
     1,
     'Lesson 3 assigns staff the first review of AI drafts, checking for obvious errors and missing elements and flagging anything not independently verified. Staff genuinely do research filing rules and genuinely do check citations in authoritative databases, which is what makes the other options feel close. The lesson still reserves the judgment calls to the supervising attorney: whether an argument is supported, which authority binds, and whether a document may be filed.',
     'L3:staff-scope',
     3),
    (v_course_id,
     'Two staff members are each asked to pull names, addresses and case types from fifty case files. One pastes the files into a consumer chatbot; the other builds a firm-approved automation. What makes one compliant and the other not?',
     '["The volume of files, since fifty exceeds what a chat window handles reliably", "The second staff member''s authorization level", "The output format, since the automation writes directly into the case system", "The route the client data takes, not the task being performed"]'::jsonb,
     3,
     'This is Lesson 4''s Amanda and Paul scenario, and the lesson''s own summary is that the same task can be compliant or non-compliant depending on the route the data takes. Volume really is impractical in a chat window, authorization really does matter generally, and the compliant automation really does end by writing to the client file. But the task here is identical in both cases, and only the data path differs.',
     'L4:data-route',
     4),
    (v_course_id,
     'The course compares an API to checking in at a building''s front desk. What does that analogy illustrate?',
     '["That every request is verified, and only what was authorized comes back", "That requests are logged, so misuse can be traced afterward", "That data is encrypted while moving between systems", "That access is granted once and then persists for the rest of the session"]'::jsonb,
     0,
     'Lesson 4 uses the front desk for verification and scope: you show ID, the desk confirms who you are, and you are handed exactly one key, the one to your own unit, with nothing else in the building exposed. Logging, encryption and session persistence are all real properties of real APIs. The lesson''s contrast, though, is with a chatbox, which has no checkpoint at all, so whatever is typed is treated as fully trusted and the only outcome available is full access.',
     'L4:api-scope',
     4),
    (v_course_id,
     'A vendor markets its AI chat product as a secure business tier with data isolation. When may staff use it for confidential client information?',
     '["Once the business tier is active, since it is built for professional use", "Once a colleague confirms other firms use it for client work", "Once client names have been removed from anything entered into it", "Only once the firm has specifically approved that tool for that purpose"]'::jsonb,
     3,
     'Lesson 4 states that even a chatbox labeled business or secure should not be used for client information unless the firm has specifically approved it for that purpose. Business tiers genuinely do carry stronger terms than consumer ones, and peer adoption genuinely is signal about a product. But Lesson 5 warns that popularity does not guarantee a tool meets the firm''s requirements, and Lesson 2 already established that removing names is not sufficient.',
     'L4:business-label',
     4),
    (v_course_id,
     'A proposed workflow routes intake data through an outside vendor. It was designed with a security review, and staff have been trained on it, but no confidentiality agreement with the vendor has been signed. Under Lesson 4 the workflow is:',
     '["Approved, since the security review is the substantive requirement and training has already been completed", "Approved for non-sensitive fields while the agreement is finalized, provided no client identifiers are sent", "Not approved, because a signed vendor agreement is required before confidential data moves through it", "Not approved, but usable if a supervising attorney authorizes it case by case and documents the decision"]'::jsonb,
     2,
     'Lesson 4 gives three requirements together: design and security, vendor agreements, and policy and training. It states that without a signed agreement and a security review, a workflow involving outside vendors should never be used for confidential client data. The security review really is the most substantive piece, field-level scoping really is a genuine mitigation, and attorney authorization really is the escalation route elsewhere in the course. But the criteria are cumulative rather than a majority vote, and the lesson offers no override for a missing agreement.',
     'L4:approval-criteria',
     4),
    (v_course_id,
     'Which statement matches Lesson 4''s description of staff responsibility for workflow compliance?',
     '["Staff must confirm a workflow is technically secure before using it with client data", "Staff carry no responsibility, since compliance is the supervising attorney''s duty", "Staff may authorize a workflow themselves when no supervisor is available and the matter is urgent, provided they report it afterward", "Staff must use only approved workflows and escalate when unsure, without being expected to judge technical compliance"]'::jsonb,
     3,
     'Lesson 4 states plainly that staff are not expected to determine the technical details of compliance, but must know when to escalate questions or concerns, and that protecting client data is a shared responsibility. Staff are expected to understand the basics of vendor evaluation under Lesson 5, the formal supervisory duty really does sit with the attorney, and deadline pressure really is a live constraint. None of that removes the obligation to use approved workflows and to stop and ask.',
     'L4:staff-scope',
     4),
    (v_course_id,
     'A staff member is helping design a new automation and needs to test how it handles a matter file. Lesson 4''s guidance is to use:',
     '["Placeholder data, never real client files pasted into the chat window", "A real client file, since the automation is the approved route for client data", "A real file from a closed matter, since that case is no longer active", "A real file with the names and dates replaced"]'::jsonb,
     0,
     'Lesson 4''s guidance for helping design a new automation is to use placeholders for client data and never paste real files into the chat window, summarized as: AI needs the recipe, not the client''s file. The automation genuinely is the approved route once it is running, closed matters genuinely feel lower-risk, and substitution genuinely is a real anonymization technique. But design work happens in a chat window outside that approved route, closed matters remain confidential, and Lesson 2 showed that swapping names and dates leaves an identifying fact pattern intact.',
     'L4:placeholder-data',
     4),
    (v_course_id,
     'In Lesson 4''s walkthrough of a compliant automation, what happens to the finished output?',
     '["It is returned to the staff member to paste into the client file", "It is saved directly to the client file inside the firm''s system", "It is held by the vendor until an attorney approves its release", "It is emailed to the supervising attorney for review"]'::jsonb,
     1,
     'Lesson 4''s four-step journey ends with the output saved directly to the client file within the firm''s system, stressing that at no point is the data pasted into a public chatbox or sent to an unapproved platform. Attorney review genuinely is required before client-facing use under Lesson 3, and vendor-side holds genuinely do exist in some products. But those are separate obligations from where the automation writes, and a manual paste step would reintroduce the exposure the design exists to avoid.',
     'L4:output-destination',
     4),
    (v_course_id,
     'Which of these is an unapproved workflow as Lesson 4 defines the term?',
     '["An automation that saves intake forms directly into the case management system", "Using a new AI tool for a client task without checking whether it is authorized", "An approved tool that this particular staff member has never used before", "A vendor workflow covered by a signed confidentiality agreement and a security review"]'::jsonb,
     1,
     'Lesson 4 defines unapproved workflows as ad hoc or manual processes, giving using a new AI tool without checking if it is authorized as its example. Its sorting exercise places the intake automation and the agreement-backed vendor workflow in the approved column. Unfamiliarity is a genuine reason to ask how to use something correctly, which the course encourages throughout, but it does not make an approved workflow unapproved.',
     'L4:unapproved-recognition',
     4),
    (v_course_id,
     'A staff member sees a colleague pasting client notes into a consumer chatbox. Lesson 4''s recommended response is to:',
     '["Report the colleague to the supervising attorney without speaking to them first, since the disclosure has already happened", "Say nothing, since workflow compliance is the firm''s responsibility rather than a peer''s", "Tell them it is not an approved workflow, and point them to the secure automation or the supervising attorney", "Ask them to delete the conversation and treat the matter as resolved once it is gone from the account"]'::jsonb,
     2,
     'Lesson 4''s What Should You Do panel answers this directly: remind them this is not an approved workflow and advise them to use the secure automation or check with the supervising attorney. Escalation is legitimate and sometimes necessary, the firm genuinely does set policy, and deleting the conversation is a sensible immediate step. But Lesson 2 explains the disclosure already occurred on entry, so deletion does not close the matter, and Lesson 1 makes speaking up a shared responsibility.',
     'L4:colleague-intervention',
     4),
    (v_course_id,
     'A staff member wants to ask an AI tool for ideas on improving a firm workflow. No client matter is involved. Under Lesson 4 this is:',
     '["Prohibited, since all AI use for firm work requires prior approval", "Acceptable only inside an approved automation, not in a chatbox", "Acceptable only if a supervising attorney reviews the ideas first", "Acceptable, since no client data is involved"]'::jsonb,
     3,
     'Lesson 4''s distinction turns on the route client data takes, and a general request for workflow improvement ideas involves no client data at all, which is why the lesson places that prompt on the chatbox side of its sorting exercise. Approval, approved automations and attorney review all matter enormously once client information is in play, and each is the right answer to a nearby question. The course does not treat every AI interaction as requiring them.',
     'L4:no-client-data',
     4),
    (v_course_id,
     'A staff member uses an AI chatbot to respond to a client question about their legal matter without attorney review. The primary ethics concern is:',
     '["The client may prefer communicating with a human, and the firm''s relationship with them depends on that contact", "The AI response may constitute unauthorized practice of law and risk exposing confidential client data", "The AI chatbot may respond more slowly than a human during periods of heavy demand", "The client''s question might be too complex for the AI tool to answer without more context"]'::jsonb,
     1,
     'Having non-lawyer staff deliver legal advice via AI — even if the staff member is not themselves giving the advice — risks unauthorized practice of law and may expose privileged client communications to third-party AI systems.',
     'L5:upl-risk',
     5),
    (v_course_id,
     '"Reasonable supervision" of staff AI use most likely requires:',
     '["Reviewing every single AI-generated output before any use, regardless of task", "Banning all AI tools firm-wide to eliminate supervision risk entirely", "Establishing firm AI policies and periodically reviewing staff AI outputs", "Delegating all supervision responsibility to the most senior paralegal"]'::jsonb,
     2,
     'Reasonable supervision is context-dependent. It typically means setting clear firm policies on approved AI tools and appropriate use cases, providing staff training, and spot-checking outputs — not reviewing every keystroke.',
     'L5:reasonable-supervision',
     5),
    (v_course_id,
     'Which task may a staff member typically handle independently using a firm-approved AI tool?',
     '["Drafting a substantive reply to a client''s question about their matter", "Summarizing confidential client notes for the file", "Deciding whether a new AI tool is suitable for client data", "Formatting a document with an approved template"]'::jsonb,
     3,
     'Lesson 5 places routine administrative tasks such as formatting documents and using approved templates in the independent-use category, because they involve neither legal judgment nor confidential client data. Drafting client-facing content and handling client information both require attorney oversight under the same lesson. Summarizing attorney notes is genuinely something a vetted automation can do, per Lesson 4, but not something staff decide to do unsupervised, and vendor evaluation is explicitly an escalation rather than an independent call.',
     'L5:independent-use',
     5),
    (v_course_id,
     'A staff member evaluating a new AI vendor confirms the product is encrypted in transit and at rest, and that several peer firms use it. Which of the course''s vendor criteria is still unanswered?',
     '["Whether the vendor retains, reviews, or trains on the data users enter", "Security practices, such as encryption and access controls", "Whether the product comes with a support agreement", "Whether the vendor is well established in the legal market and used by comparable firms"]'::jsonb,
     0,
     'Lesson 5 lists four criteria: a confidentiality agreement, retention policies, jurisdiction, and security practices. Encryption genuinely does address security practices, and peer adoption genuinely does speak to market standing, so both of those have been partly answered. The lesson warns that vendors who keep or train on data may expose confidential information even while claiming to be secure, and states directly that popularity does not guarantee a tool meets the firm''s requirements.',
     'L5:vendor-retention',
     5),
    (v_course_id,
     'A firm''s video platform enables an AI notetaker by default. It joins a privileged client call and transcribes it to a third-party cloud. The primary concern is:',
     '["The transcript may contain errors that mislead whoever reads it later in the matter", "The recording may count as disclosing a privileged conversation to a third party", "The notetaker was never put through the firm''s vendor review or security assessment", "Participants were not told the call was being recorded"]'::jsonb,
     1,
     'Lesson 5''s uninvited AI guest scenario states that because client calls are often privileged, letting an outside AI tool record and store the conversation can count as disclosing it to a third party and can risk the privilege itself, whether or not anyone meant to invite the tool in. Transcription errors, the missing vendor review, and the absence of recording notice are all genuine problems in this scenario. The privilege is the one that can be lost and not recovered.',
     'L5:bundled-ai',
     5),
    (v_course_id,
     'A staff member encounters an AI feature that no firm checklist or policy addresses. Lesson 5''s guidance is to:',
     '["Treat it as permitted, since nothing in current firm policy prohibits it and staff cannot wait on every update", "Treat it as prohibited until firm policy is formally updated to address it", "Apply the firm''s core principles of confidentiality, accuracy and supervision, and escalate if doubt remains", "Ask the vendor whether the feature is appropriate for legal use, since they know its data handling best"]'::jsonb,
     2,
     'Lesson 5 acknowledges that technology changes faster than checklists, and instructs staff to apply the firm''s core principles to any new scenario, escalating when in doubt. Caution genuinely is the right instinct and pausing genuinely is what the lesson asks for, and the vendor genuinely does hold the technical facts. But a blanket prohibition is not what the course prescribes, and the same lesson warns against relying on a vendor''s own claims when evaluating a tool.',
     'L5:novel-scenario',
     5),
    (v_course_id,
     'Which staff action does Lesson 5 classify as non-compliant?',
     '["Relying on a vendor''s stated end-to-end encryption without verifying it", "Stopping to ask a supervisor when unsure whether a workflow is approved", "Escalating to an attorney when asked to paste confidential data into a chatbox", "Declining to use an unapproved tool even though a deadline is close"]'::jsonb,
     0,
     'Lesson 5''s sorting exercise places relying on a vendor''s marketing claim of end-to-end encryption without verifying it in the non-compliant column, alongside using a business-grade tool for intake without verification. Stopping to ask and escalating are both listed as compliant. Declining an unapproved tool under deadline pressure is exactly what the lesson''s daily-compliance checkpoint asks for, even though it is plainly the harder choice in the moment.',
     'L5:sorting-noncompliant',
     5),
    (v_course_id,
     'A client emails asking whether they should accept a settlement offer. A staff member drafts a reply using a firm-approved AI tool, proofreads it, and sends it. The problem is:',
     '["That an AI tool was used for client communication at all, rather than a person the client knows and trusts", "That the staff member proofread it rather than having the AI verify its own output", "That the email should have been routed through an automation rather than a chatbox", "That the reply gives legal advice, which requires attorney authorization regardless of the tool"]'::jsonb,
     3,
     'Lesson 5''s daily-compliance checkpoint says never to provide legal advice through AI without explicit authorization from a supervising attorney, and Lesson 5''s existing question treats this as risking unauthorized practice of law. The approved tool genuinely does address the confidentiality route, proofreading genuinely is better than not, and the data route genuinely does matter. None of them reaches the substantive problem: whether to accept a settlement is legal judgment, which is not the staff member''s to give however the words were drafted.',
     'L5:legal-advice',
     5),
    (v_course_id,
     'Lesson 5 describes gray areas as situations not clearly covered by existing policies or checklists. What does it prescribe for them?',
     '["Use professional judgment and proceed, documenting the reasoning", "Default to the most restrictive reading of the nearest applicable policy", "Pause and consult a supervisor or check firm policy before acting", "Treat them as approved if a similar workflow has already been approved"]'::jsonb,
     2,
     'Lesson 5 states that in gray areas the safest approach is to pause and consult a supervisor or check firm policy before taking action, and that escalating early prevents mistakes and demonstrates a commitment to compliance. Documenting reasoning, reading conservatively, and reasoning from analogous approvals are all defensible professional habits. Each of them, though, has the staff member resolving the question alone, when the lesson asks them to hand it to someone with the authority to answer it.',
     'L5:gray-areas',
     5),
    (v_course_id,
     'Lesson 5 gives a sequence for handling a new AI tool. After recognizing the tool and checking whether the firm has approved it, what happens when the question involves vendor evaluation or system security?',
     '["Proceed within the boundaries of the staff member''s role", "Escalate to an attorney or IT specialist for review", "Pause until the tool appears on the firm''s approved list", "Request the vendor''s security documentation and assess it"]'::jsonb,
     1,
     'Lesson 5''s sequence routes vendor evaluation and system security questions to an attorney or IT specialist for a thorough review, consistent with Lesson 4''s statement that staff are not expected to determine technical compliance. Proceeding within boundaries is right once a tool is approved, waiting for the approved list is safe, and someone really does need to request the vendor''s documentation. That assessment is the escalation target''s work rather than the staff member''s.',
     'L5:escalation-target',
     5);
  get diagnostics v_inserted = row_count;

  raise notice '0026: retired % question(s), inserted %.', v_retired, v_inserted;

  -- 3. Fail loudly if the pool cannot satisfy the 1/2/2/1/2 blueprint.
  if exists (
    select 1
      from (values (1,1),(2,2),(3,2),(4,1),(5,2)) as need(lesson, required)
      left join (
        select lesson, count(*) as have
          from public.quiz_questions
         where course_id = v_course_id and is_active = true
         group by lesson
      ) got on got.lesson = need.lesson
     where coalesce(got.have, 0) < need.required
  ) then
    raise exception '0026: a lesson cannot meet its per-attempt quota. Aborting.';
  end if;
end;
$$;
